version: '3'
services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: hotwire_demo
    ports:
      - '3307:3306'
    volumes:
      - mysql:/var/lib/mysql
  redis:
    image: redis:latest
    ports:
      - 6379:6379
volumes:
  mysql:
    driver: local
